//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class GOITAP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GOITAP()
        {
            this.LICHSUGOITAPs = new HashSet<LICHSUGOITAP>();
        }
    
        public int MAGOITAP { get; set; }
        public string TENGOITAP { get; set; }
        public int MAMONTAP { get; set; }
        public int GIAGOITAP { get; set; }
        public string GHICHU { get; set; }
        public bool XOA { get; set; }
    
        public virtual MONTAP MONTAP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICHSUGOITAP> LICHSUGOITAPs { get; set; }
    }
}
