//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICHSUGOITAP
    {
        public int id { get; set; }
        public int MATHETAP { get; set; }
        public int MAGOITAP { get; set; }
        public int MALOAIGOITAP { get; set; }
        public Nullable<int> MAPT { get; set; }
        public System.DateTime NGAYDANGKY { get; set; }
        public System.DateTime NGAYHETHAN { get; set; }
        public bool XOA { get; set; }
    
        public virtual GOITAP GOITAP { get; set; }
        public virtual LOAIGOITAP LOAIGOITAP { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
        public virtual THETAP THETAP { get; set; }
    }
}
