//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyPhongGymNTNEntities : DbContext
    {
        public QuanLyPhongGymNTNEntities()
            : base("name=QuanLyPhongGymNTNEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GOITAP> GOITAPs { get; set; }
        public virtual DbSet<LICHSUGOITAP> LICHSUGOITAPs { get; set; }
        public virtual DbSet<LICHTAP> LICHTAPs { get; set; }
        public virtual DbSet<LOAIGOITAP> LOAIGOITAPs { get; set; }
        public virtual DbSet<LOAITAIKHOAN> LOAITAIKHOANs { get; set; }
        public virtual DbSet<MONTAP> MONTAPs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TAIKHOAN> TAIKHOANs { get; set; }
        public virtual DbSet<THETAP> THETAPs { get; set; }
    }
}
