//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class THETAP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THETAP()
        {
            this.LICHSUGOITAPs = new HashSet<LICHSUGOITAP>();
        }
    
        public int MATHETAP { get; set; }
        public int MAKHACHHANG { get; set; }
        public bool KHOA { get; set; }
        public bool XOA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICHSUGOITAP> LICHSUGOITAPs { get; set; }
        public virtual LICHTAP LICHTAP { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
    }
}
